### ISSUE TITLE
How to download public community photos?

### ISSUE THREAD

**Issue by estatistics** [yks72p/vk_album_downloader#13]
Hello, the program cant work with 2-step verification. It must be deactivated
Also, community photos dont contain in their urls "album" word. Therefore, the program cannot download them.

How i can download community photos in vk?

Sincerely,
Elias

**Comment by navalnica** [comment]
Hi @estatistics!

As stated in readme:
> script yet can not download any special albums such as 'Saved images', 'Profile images', 'Images from wall'

Probably that is the case with Community photos as well.

As for 2-step verification, the script was written without support for this authorization flow. Currently, I have no time to fix it. But it should be possible, I guess. There is `auth_handler` parameter in `vk_api.VkApi.__init__()` method that seems to handle 2fa. You can check details in the official [vk_api documentation ](https://vk-api.readthedocs.io/en/latest/vk_api.html). It's in russian, but you can translate it using Google Chrome.

If you manage to fix some errors, feel free to propose your edits using a Pull Request!

**Comment by estatistics** [comment]
thanks
