### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ravinot** [yks72p/vk_album_downloader#3]
Hello,

Thank you for writing this script. I was able to install and run, but when I tried to download the first album the following error appeared:

Traceback (most recent call last):
  File "vk_album_downloader.py", line 152, in <module>
    main()
  File "vk_album_downloader.py", line 143, in main
    extension = re.findall(r'\.[\w\d.-]+$', largest_image_src)[0]
IndexError: list index out of range

I'm not sure how to fix it, can you please advise?

**Comment by alerikaisattera** [comment]
Replace line 143 with

extension = ".jpg"

**Comment by ravinot** [comment]
Thank you for the reply, I tried the fix as per https://github.com/yks72p/vk_album_downloader/pull/4 and it works.

**Comment by DennisPing** [comment]
Thank you, the fix worked.

**Comment by navalnica** [comment]
Fixed extension parsing in #10  :)
