### ISSUE TITLE
Album size stuck at 50 - add one more parameter to method

### ISSUE THREAD

**Issue by DennisPing** [yks72p/vk_album_downloader#6]
### Issue:
The album max size is stuck at 50.
According to the vk_api (https://vk.com/dev/photos.get) the default value is 50. Add one more parameter so that you can download more than 50 images from an album.

### Line 115:
`photos = api.photos.get(owner_id=o, album_id=a, photo_sizes=1)['items']`

### Add parameter 'count':
`photos = api.photos.get(owner_id=o, album_id=a, photo_sizes=1, count=images_num)['items']`

(Sorry, I am a student and have not learned how to do pull requests)

**Comment by navalnica** [comment]
@DennisPing thanks for the comment! I'm planning to rewrite the script soon and fix your issue as well

**Comment by navalnica** [comment]
Fixed by @donmor in #8 
Thanks for contribution!
